# Generated by Django 4.0.6 on 2023-01-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
