# Generated by Django 4.0.6 on 2022-08-02 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('unitcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='vcard',
            field=models.FileField(default=django.utils.timezone.now, upload_to='card/'),
            preserve_default=False,
        ),
    ]
