# Generated by Django 4.0.6 on 2022-08-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitcard', '0002_card_vcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='vcard',
            field=models.FileField(upload_to=''),
        ),
    ]
