# Generated by Django 4.0.6 on 2022-12-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitcard', '0003_alter_card_vcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filecard', models.FileField(upload_to='card/')),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='vcard',
            field=models.FileField(upload_to='card/'),
        ),
    ]
